### ISSUE TITLE
Repo klonen auf Windows nicht möglich

### ISSUE THREAD

**Issue by vd-aloker** [thinktecture-labs/basta-2024-gen-ai-workshop#1]
Beim Versuch, das Repo auf einen Windows Rechner zu klonen, bekomme ich Fehler, da einige Pfade nicht kompatibel mit NTFS sind:

error: invalid path 'links/The latest in Machine Learning | Papers With Code.webloc'
error: invalid path 'links/ggerganov - llama.cpp- LLM inference in C:C++.webloc'
error: invalid path 'links/langchain-ai:langchain- ­ƒª£­ƒöù Build context-aware reasoning applications.webloc'
error: invalid path 'links/openai:openai-dotnet- The official .NET library for the OpenAI API.webloc'

Es geht hier insbesondere um |, : und die Emojis. Könntet ihr die Pfade ggf. anpassen? Danke!

**Comment by gingters** [comment]
Danke für den Hinweis.
Links sind angepasst und es sollte sich jetzt auf Windows auschecken lassen. Falls nicht, bitte nochmal melden.
